version: '3.9'
services:
    app:
        build:
            context: .
            dockerfile: docker-config/Dockerfile
        image: malsanyang.com/laravel.test
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-8000}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${DOCKER_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${DOCKER_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - laravel
    mariadb:
        image: 'mariadb:10'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'mariadb:/var/lib/mysql'
        networks:
            - laravel
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
            retries: 3
            timeout: 5s
    phpmyadmin:
        image: phpmyadmin:latest
        ports:
            - '${FORWARD_PHPMYADMIN_PORT_PORT:-8080}:80'
        environment:
            - PMA_HOST=mariadb
            - PMA_PASSWORD=${DB_PASSWORD}
            - PMA_UPLOAD_LIMIT=100M
            - UPLOAD_LIMIT=100M
        networks:
            - laravel

networks:
    laravel:
        driver: bridge

volumes:
    mariadb:
        driver: local
